homepage/urls.py
from django.urls import path
from django.contrib import admin
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('schedule/', views.schedule, name='schedule'),
    path('schedule/create', views.create_schedule, name='create_schedule'),
    path('schedule/clear/<int:id>/', views.delete_schedule, name='delete_schedule'),
]

webodi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime, date

# Create your models here.


class Schedule(models.Model):
    day = models.CharField('day', max_length = 30)
    date = models.DateTimeField(default = datetime.now)
    time = models.TimeField()
    activity = models.CharField('activities', max_length=30)
    place = models.CharField('place', max_length=30)
    category = models.CharField('category', max_length=30)

    def __str__(self):
        return self.activity

homepage/forms.py
from django import forms
from .models import Schedule



class ScheduleForm(forms.ModelForm):

    class Meta:
        model = Schedule
        fields = ['activity', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from datetime import datetime, date
from .models import Schedule
from . import forms

def home(request):
    return render(request, 'home2.html')

def profile(request):
    return render(request, 'profile.html')

def portfolio(request):
    return render(request, 'portt.html')

def schedule(request):
	schedules = Schedule.objects.all().values().order_by('date')
	return render(request, 'schedule.html', {'schedules': schedules})

def create_schedule(request):
	if request.method == 'POST':
		form = forms.ScheduleForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('homepage:schedule')
	else:
		form = forms.ScheduleForm()
	
	return render(request, 'create_schedule.html', {'form': form})

def delete_schedule(request, id):
	 if request.method == 'POST':
		 Schedule.objects.filter(id=id).delete()
		 return redirect('homepage:schedule')
	 else:
		 return HttpResponse("/GET not allowed")

homepage/templates/create_schedule.html
{% load static %}


{<!DOCTYPE html>
    
    <html>
        <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                <link rel="icon" href="{% static 'images/odilog white.png' %}" type="image/png" sizes="40x40">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
                <link rel="stylesheet" href="{% static 'css/webCSS.css' %}" type="text/CSS">
                <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
                <link href='https://fonts.googleapis.com/css?family=GFS Didot' rel='stylesheet'>
                <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
                <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">
                <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <title>Schedule</title>
        </head>
    
    <body> 
            <nav class="navbar navbar-light bg-white fixed-top">
                    <a class="navbar-brand" href="#">
                        <img class ="img-fluid" id="logo" src="{% static 'images/odilog.png' %}" alt="odi logo"></img>
                    </a>
                    <ul class="navbar-nav list-group-horizontal">
                      <li class="list-group-items"><a class="home" href="/">home</a></li>
                      <li class="list-group-items"><a class="home" href="/profile">profile</a></li>
                      <li class="list-group-items"><a class="home" href="/portfolio/">portfolio</a></li>
                      <li class="list-group-items"><a class="home" href="/#contactPage">contact</a></li>
                      <li class="list-group-items"><a class="home" href="/schedule">schedule</a></li>
                    </ul>
                   </nav>

                   <p id="ScheduleTitle">Schedule</p>
        

<form class="css" action="{% url 'homepage:create_schedule' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-sm-1"></div>
            <div class="form-group col-sm-10">
                {% for fields in form %}
                    {{ fields.label_tag }}
                    <br>
                    {{ fields }}
                    <br>
                {% endfor %}
            </div>
        </div>
        <div class="form-row">
            <div class="col-sm-1"></div>
            <input type="submit" class="btn btn-add float-right" value="Add">
        </form>
       
        <div class="footer">
                <img id=logoFoot src="{% static 'images/odilog white.png' %}"></img>
        </div>

    </body>
    </html>
            

homepage/templates/home2.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
            <link rel="icon" href="{% static 'images/odilog white.png' %}" type="image/png" sizes="40x40">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/webCSS.css' %}" type="text/CSS">
            <link href='https://fonts.googleapis.com/css?family=GFS Didot' rel='stylesheet'>
            <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
            <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Home</title>
    </head>
<body class="homeBody"> 
    <nav class="navbar navbar-light bg-white fixed-top">
        <a class="navbar-brand" href="#">
            <img class ="img-fluid" id="logo" src="{% static 'images/odilog.png' %}" alt="odi logo"></img>
        </a>
        <ul class="navbar-nav list-group-horizontal">
          <li class="list-group-items"><a class="home" href="/">home</a></li>
          <li class="list-group-items"><a class="home" href="/profile">profile</a></li>
          <li class="list-group-items"><a class="home" href="/portfolio/">portfolio</a></li>
          <li class="list-group-items"><a class="home" href="/#contactPage">contact</a></li>
          <li class="list-group-items"><a class="home" href="/schedule">schedule</a></li>
        </ul>
       </nav>
      
        <div class="container section-container" id="homePage">
        <div class="center">
            <h1>Hello,</h1>
            <h2><span></span></h2>
        </div>
      </div>
        

      <div class="container section-container" id="contactPage">
          <div class="center2">
              <h1 id ="contactTitle">Let's get in touch!</h1>
            <br>
            <br>
            
              <div class="container logoSocialMedia justify-content-center">
                <div class="row justify-content-center">
                  <div class="col-md-4">
                    <div class="text-center">
                        <img class=socLogo src="{% static 'images/line.png' %}">
                        <p class=socText>Audillapfme</p>
                    </div>
                      
                  </div>
                  <div class="col-md-4">
                    <div class="text-center">
                        <img class=socLogo src="{% static 'images/mail.png' %}">
                        <p class=socText>audipfme@gmail.com</p>
                    </div> 
                  </div>
                  <div class="col-md-4">
                    <div class="text-center">
                        <img class=socLogo src="{% static 'images/phone.png' %}">
                        <p class=socText>087787239689</p>
                    </div>
                      
                  </div>
          </div>
          <br>
          <br>
          <br>
          <div class="row justify-content-center">
            <div class="col-xs-4">
              <div class="text-center">
                  <a href="https://www.linkedin.com/in/audilla-putri-ferialdi-b92139186/" target='_blank'>
                    <img class="socLogo2" src="{% static 'images/in.png' %}"></img>
                </a>
              </div>
                
            </div>
            <div class="col-xs-4">
              <div class="text-center">

                <a href="https://www.instagram.com/audillapf/" target='_blank'>
                  <img class="socLogo2" src="{% static 'images/ig.png' %}"></img>
                  
              </a>
              </div>
            </div>
            <div class="col-xs-4">
              <div class="text-center">
                  <a href="https://open.spotify.com/user/odillapf?si=-A3PxZBAQeSHH8CGDO5WmQ" target='_blank'>
                    <img class="socLogo2" src="{% static 'images/sptfy.png' %}" alt="spotify icon"></img>
                </a>
              </div>
                
            </div>
          </div>

</div>
          </div>
      </div>

        <div class="footer">
                <img id=logoFoot src="{% static 'images/odilog white.png' %}"></img>
           </div>
       
</body>
</html>

homepage/templates/portt.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="icon" href="{% static 'images/odilog white.png' %}" type="image/png" sizes="40x40">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/webCSS.css' %}" type="text/CSS">
            <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
            <link href='https://fonts.googleapis.com/css?family=GFS Didot' rel='stylesheet'>
            <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">
            
    <title>Portfolio</title>
    </head>

<body> 
                <nav class="navbar navbar-light bg-white fixed-top">
                                <a class="navbar-brand" href="#">
                                    <img class ="img-fluid" id="logo" src="{% static 'images/odilog.png' %}" alt="odi logo"></img>
                                </a>
                                <ul class="navbar-nav list-group-horizontal">
                                  <li class="list-group-items"><a class="home" href="/">home</a></li>
                                  <li class="list-group-items"><a class="home" href="/profile">profile</a></li>
                                  <li class="list-group-items"><a class="home" href="/portfolio/">portfolio</a></li>
                                  <li class="list-group-items"><a class="home" href="/#contactPage">contact</a></li>
                                  <li class="list-group-items"><a class="home" href="/schedule">schedule</a></li>
                                </ul>
                               </nav>

        <p  class ="portfolioTitle">Portfolio</p>

    <div class="container-fluid allContent">
        <div class="row">
            <div class="col">
                <div class="text-center">
                        <p class="editorialtitle">EDITORIAL</p>
                </div>
                    
            </div>
                
        </div>
        
        <div class="row">
        <div class="container editorial justify-content-center">
            <div class="col-xs-4 ">
                <div class="text-center">
                        <img id="ed1" src="{% static 'images/Cover takitrii copy.jpg' %}"></img>
                        <br>
                        <p class="imgText" >Takitri Magazine <br> by Media Siswa SMAN 8 2016</p>
                </div>
                    
            </div>
            <div class="col-xs-4">
                    <div class="text-center">
                    <img id="ed2" src="{% static 'images/01-Cover-Depan.jpg' %}"></img>
                    <br>
                    <p class="imgText" >Takitri Magazine <br> by Media Siswa SMAN 8 2017</p>
                    </div>
            </div>
            <div class="col-xs-4">
                    <div class="text-center">
                    <img id="ed3" src="{% static 'images/Did you know  copy.jpg' %}"></img>
                    <br>
                    <p class="imgText" >FunFact page <br> in Takitri 2016</p>
                    </div>
            </div>
        </div>
    </div>
    <br>
    <br>
    <div class="row">
            <div class="col ">
                    <p class="editorialtitle">POSTER DESIGN</p>
            </div>
    </div>
    
        <div class="row">
                        <div class="container poster">
            <div class="col-md-auto">
                    <div class="text-center">
                    <img id="botImg1" src="{% static 'images/hi.jpg' %}"></img>
                    <br>
                    <p class="botText" >Gelar Karya 2018 <br> “Discode”, H-4 Countdown</p>
                    </div>
            </div>
            <div class="col-md-auto">
                    <div class="text-center">
                    <img id="botImg2" src="{% static 'images/Poster GelarKarya 2018.jpg' %}"></img>
                    <br>
                    <p class="botText" id="botText2">Gelar Karya 2018 <br>“Discode”</p>
                    </div>
            </div>
        </div>

        </div>
    </div>

    <div class="footer">
            <img id=logoFoot src="{% static 'images/odilog white.png' %}"></img>
    </div>


</body>
</html>

homepage/templates/profile.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="icon" href="{% static 'images/odilog white.png' %}" type="image/png" sizes="40x40">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
            <link rel="stylesheet" href="{% static 'css/webCSS.css' %}" type="text/CSS">
            <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
            <link href='https://fonts.googleapis.com/css?family=GFS Didot' rel='stylesheet'>
            <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
            <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>Profile</title>
    </head>

<body> 
        <nav class="navbar navbar-light bg-white fixed-top">
                <a class="navbar-brand" href="#">
                    <img class ="img-fluid" id="logo" src="{% static 'images/odilog.png' %}" alt="odi logo"></img>
                </a>
                <ul class="navbar-nav list-group-horizontal">
                  <li class="list-group-items"><a class="home" href="/">home</a></li>
                  <li class="list-group-items"><a class="home" href="/profile">profile</a></li>
                  <li class="list-group-items"><a class="home" href="/portfolio/">portfolio</a></li>
                  <li class="list-group-items"><a class="home" href="/#contactPage">contact</a></li>
                  <li class="list-group-items"><a class="home" href="/schedule">schedule</a></li>
                </ul>
               </nav>

<div class="container-fluid allProf justify-content-md-center">
    <div class="row">
        <div class="col-md-auto ">
            <div class="container justify-content-md-center">
            <p id="name">Audilla Putri</p>
            <br>
            <br>
            <br>
            <img  class=fotoaku src ="{% static 'images/hihibaru.jpg' %}">
        </div>
        </div>
        
        <div class="col-md-8">
            <div class="container" id="myGroup">
                    <br>
                    
                    <button class="btn btn-profile" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample"><i class="far fa-user"></i>
                        Profile
                    </button>
                    <button class="btn btn-profile" type="button" data-toggle="collapse" data-target="#collapseExample2" aria-expanded="false" aria-controls="collapseExample2"><i class="fas fa-graduation-cap"></i>
                        Education
                    </button>
                    <button class="btn btn-profile" type="button" data-toggle="collapse" data-target="#collapseExample3" aria-expanded="false" aria-controls="collapseExample3"><i class="fas fa-briefcase"></i>
                            Experience
                    </button>
                    <br>
                    <br>
                    <div class="collapse show" id="collapseExample" data-parent="#myGroup">
                            <div class="card card-body">
                                <p class="Title">Hi, I'm Odi</p>
                                <p id="introtext"> I’m an enthusiastic and hard-working individual who’s passionate about designing. I’m currently studying Computer Science in Universitas Indonesia. I’m able to work both as a team and as an individual. I’m adhere to strict deadlines and able to work under pressure.</p>
                            </div>
                        </div>
                        <div class="collapse" id="collapseExample2" data-parent="#myGroup">
                            <div class="card card-body2">
                                <p class="Title">Education</p>
                                <ul class="list-unstyled">
                                    <li class="media">
                                      <img class="mr-3" src="{% static 'images/pacil.png' %}" alt="Generic placeholder image">
                                      <div class="media-body">
                                        <h5 class=resumess>Faculty of Computer Science, University of Indonesia</h5>
                                        2018--Now
                                      </div>
                                    </li>
            
                                    <li class="media my-4">
                                      <img class="mr-3" src="{% static 'images/sman8.png' %}" alt="Generic placeholder image">
                                      <div class="media-body">
                                        <h5 class=resumess>SMAN 8 Jakarta</h5>
                                        2015--2018
                                      </div>
                                    </li>
            
                                    <li class="media my-4">
                                        <img class="mr-3" src="{% static 'images/alazka.png' %}" alt="Generic placeholder image">
                                        <div class="media-body">
                                          <h5 class=resumess>SMPI Al-Azhar Kelapa Gading</h5>
                                          2013--2015
                                         </div>
                                    </li>
                                    <li class="media my-4">
                                        <img class="mr-3" src="{% static 'images/alazka.png' %}" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <h5 class=resumess>SDI Al-Azhar Kelapa Gading</h5>
                                            2008--2013
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
            
            
                        <div class="collapse" id="collapseExample3" data-parent="#myGroup">
                            <div class="card card-body2">
                                <p class="Title">Experience</p>
                                <ul class="list-unstyled">
                                    <li class="media">
                                        <img class="mr-3" src="{% static 'images/senbud.png' %}" alt="Generic placeholder image">
                                        <div class="media-body">
                                            <h5 class=resumess>Student Executive Board</h5>
                                                Staff of Department of Art and Culture - 2019
                                        </div>
                                    </li>
                                    <li class="media my-4">
                                      <img class="mr-3" src="{% static 'images/compfest.jpg' %}" alt="Generic placeholder image">
                                      <div class="media-body">
                                        <h5 class=resumess>Compfest XI 2019</h5>
                                        Staff of Fundraising Division - 2019
                                      </div>
                                    </li>
                                    <li class="media my-4">
                                        <img class="mr-3" src="{% static 'images/dscd.jpg' %}" alt="Generic placeholder image">
                                        <div class="media-body">
                                          <h5 class=resumess>Gelar Karya "Discode"</h5>
                                          Head of Visual Design Divison - 2018
                                        </div>
                                    </li>
                                    <li class="media my-4">
                                        <img class="mr-3" src="{% static 'images/mesis.png' %}" alt="Generic placeholder image">
                                        <div class="media-body">
                                          <h5 class=resumess>Media Siswa 29 SMAN 8 Jakarta</h5>
                                          Head of Graphic Design Division - 2017
                                        </div>
                                    </li>
                                </ul>      
                            </div>
                        </div>
                    </div>
                </div>        
        </div>
    </div>
</div>

        
</body>

</html>

homepage/templates/schedule.html
 {% load static %}
{<!DOCTYPE html>
   
    <html>
        <head>
                <meta charset="utf-8">
                <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                <link rel="icon" href="{% static 'images/odilog white.png' %}" type="image/png" sizes="40x40">
                <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
                <link rel="stylesheet" href="{% static 'css/webCSS.css' %}" type="text/CSS">
                <link href='https://fonts.googleapis.com/css?family=Abril Fatface' rel='stylesheet'>
                <link href='https://fonts.googleapis.com/css?family=GFS Didot' rel='stylesheet'>
                <script src="https://kit.fontawesome.com/1927c4eb85.js" crossorigin="anonymous"></script>
                <link href="https://fonts.googleapis.com/css?family=Be+Vietnam&display=swap" rel="stylesheet">
                <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
                <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <title>Schedule</title>
        </head>
    
    <body> 

            <nav class="navbar navbar-light bg-white fixed-top">
                    <a class="navbar-brand" href="#">
                        <img class ="img-fluid" id="logo" src="{% static 'images/odilog.png' %}" alt="odi logo"></img>
                    </a>
                    <ul class="navbar-nav list-group-horizontal">
                      <li class="list-group-items"><a class="home" href="/">home</a></li>
                      <li class="list-group-items"><a class="home" href="/profile">profile</a></li>
                      <li class="list-group-items"><a class="home" href="/portfolio/">portfolio</a></li>
                      <li class="list-group-items"><a class="home" href="/#contactPage">contact</a></li>
                      <li class="list-group-items"><a class="home" href="/schedule">schedule</a></li>
                    </ul>
                   </nav>


    
            <p id="ScheduleTitle">Schedule</p>
            <br>
            <div class="article">
                <a href="{% url 'homepage:schedule' %}"></a>
                <div class="article">
                    <div class="row">
                        {% for schedule in schedules %}
                            <div class="col-sm-4 text-center">
                                <h2 id="activityName">{{ schedule.activity }}</h2>
                                <p class="activity"><i class="far fa-calendar-alt"></i>  {{ schedule.date.date }}</p>
                                <p class="activity"><i class="far fa-clock"></i>  {{ schedule.time}}</p>
                                <p class="activity"><i class="fas fa-map-marker-alt"></i>  {{ schedule.place }}</p>
                                <p class="activity"><i class="fas fa-bars"></i>  {{ schedule.category }}</p>
                                <br>
                                <div class = 'form-group'>
                                    <form action="/schedule/clear/{{ schedule.id }}/" method="POST">
                                        {% csrf_token %}
                                        <button class="btn btn-danger" type="submit">Delete</button>
                                    </form>
                            </div>
                            <br>
                            <br>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class = 'col-md-12'>
                <div class="text-center">
                        <div class = 'form-group'>
                                <a href="{% url 'homepage:create_schedule' %}">
                                    <button type="button" class= "btn btn-secondary btn-lg btn-sm">Add Activity</button></a>
                        </div>
                </div>
                
        </div>
       
        <div class="footer">
                <img id=logoFoot src="{% static 'images/odilog white.png' %}"></img>
        </div>

    </body>
    </html>
            